# Generated by Django 2.1.2 on 2018-10-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_auto_20181016_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
